name: Text to console
on:
  push:
     branches:
[ "**" ]
  pull_request:
      branches:
      [ "**" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Date and time
        run: |
          date +"DATE: %F%nTIME: %T"
